### PR TITLE
Fixed docker installation & error

### PR DESCRIPTION
**Pull request by zephylac**
Inside `Dockerfile`:  
  * Changed ubuntu version from 17.10 to 18.04 since some Release file are no longer available.  
  * Changed the way to handle `ops_settings_docker.yml`. We had to build the image everytime to take into account the changes.
  
Inside `ops_settings_docker.yml`:  
  * Added key `concurrent_workers` with value `1` to fix error which was causing the following command to crash : `docker exec -it container_name /ops_venv/bin/python manage.py import-data`  
  
Inside `docker-compose.yml`:  
  *  Mounted volumes for `ops_settings_docker.yml`, now settings changes will only require a container restart instead of image building.

### CODE REVIEW

**Comment by TimMcCauley** [comment]
@zephylac many thanks and very helpful! Were you actually able to build `imposm.parser` with the protobuf version installed on ubuntu 18.10 via apt-get?

**Comment by zephylac** [comment]
I didn't had any regarding that. I found out that it's shouldn't work on python 3.x. But as far as today didn't had any issues.

**Comment by TimMcCauley** [comment]
@zephylac thank you for sharing the information. Could you please do me one last favour and call `protoc -v` in the docker container and paste the version in here? Thanks a bunch!!!

**Comment by zephylac** [comment]
```
protoc --version
libprotoc 3.0.0
```

**Comment by TimMcCauley** [comment]
Thank you @zephylac , yes, this `3.0.0` is the latest version I got `imposm.parser` to build with. Anything above seems to fail.. hence I would suggest to make sure that we make sure that `apt-get` installs exactly this version, what do you think? 

I just checked the docke rcontainer for the specific package version:

```apt list -a protobuf-compiler
Listing... Done
protobuf-compiler/artful,now 3.0.0-9ubuntu5 amd64 [installed]```

& 

```apt list -a libprotobuf-dev
Listing... Done
libprotobuf-dev/artful,now 3.0.0-9ubuntu5 amd64 [installed]```

Here are the available versions for bionic - https://launchpad.net/ubuntu/bionic/+package/protobuf-compiler.

Could you please try the following amends in the root `Dockerfile` and if it still works add it to the PR? 

`RUN apt-get install -y build-essential protobuf-compiler=3.0.0-9ubuntu5 libprotobuf-dev=3.0.0-9ubuntu5`

Thanks for all the help, greatly appreciated! ;-)

**Comment by zephylac** [comment]
In fact I had following version :
```
 apt-cache policy protobuf-compiler
protobuf-compiler:
  Installed: 3.0.0-9.1ubuntu1
  Candidate: 3.0.0-9.1ubuntu1
  Version table:
 *** 3.0.0-9.1ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status
````
You command didn't succeed but I had the following working:
`RUN apt-get install -y build-essential protobuf-compiler=3.0.0-9.1ubuntu1 libprotobuf-dev=3.0.0-9.1ubuntu1`

**Comment by TimMcCauley** [comment]
Ok - then that is for bionic. Sounds good, thanks! Will you edit that line and update the PR?

**Comment by zephylac** [comment]
I forgot to mention that  for `categories.yml` I also mounted volumes like this :
`./categories_docker.yml:/deploy/app/openpoiservice/server/categories/categories.yml`
which avoid to connect to docker instance to modify it. Should I had it to the PR ?

**Comment by TimMcCauley** [comment]
Yes, sounds like a smart idea.

**Pull request merged**
