### PR TITLE
Feature/multipolygon support

### PR DESCRIPTION
**Pull request by zephylac**
Added initial support for MultiPolygon. It works well but I'm not satisfied with the response.
Server is responding well to the request. The only default is that the responses are mixed.
I would expect the server to respond every features for each Polygon inside the MultiPolygon separately.

### CODE REVIEW

**Comment by TimMcCauley** [comment]
@zephylac thank you - shall we tag this as WIP?

**Comment by zephylac** [comment]
Yup, still asking myself how we could implement the parallel computation on this ?

**Comment by TimMcCauley** [comment]
Hmmm. so if a user provides a `multipolygon` consisting of 20 individual polygons and settings in the config are enabled for multiprocessing, the service would spawn multiple processes depending on the amount of cores available ( https://stackoverflow.com/questions/1006289/how-to-find-out-the-number-of-cpus-using-python )  or what is set.. what do you think?

**Comment by zephylac** [comment]
Yup it seems a good idea, we could implement a queue, and fill in response array.

**Comment by TimMcCauley** [comment]
Have you seen this @zephylac http://blog.cleverelephant.ca/2019/05/parallel-postgis-4.html ?

**Comment by zephylac** [comment]
@TimMcCauley Great article, I've just checked, by default the docker image that we are currently using is under PgSQL 11.2 and PostGIS 2.5.2 .

**Comment by zephylac** [comment]
@TimMcCauley Since PostgreSQL 12 and PostGIS 3 will be under development during several month, we can't install it via common tools. I'm trying to create custom docker image that will support both, I'm still encountering some bugs (after activating ssl). [Here is the repo](https://github.com/zephylac/postgis-parallel)

**Comment by TimMcCauley** [comment]
@zephylac understand. I think, in regards to parallelization, we could implement #68  only for postgis 3 and make use of its multiprocessing feature?

**Comment by zephylac** [comment]
@TimMcCauley Having PostgreSQL and PostGIS supporting parallelization is one part of the process.
We will support multiple client and that's ok but if on the other side we can multiprocess a multipolygon. We should win some time on that type of request ? What do you think ?

**Comment by zephylac** [comment]
I tried to understand and find where I could split the response to get an array corresponding to the MultiPolygon given. I ended up [here](https://github.com/GIScience/openpoiservice/blob/master/openpoiservice/server/api/query_builder.py#L101-L118)
But I can't see how we could achieve it ? Would it it another groupby ?

**Comment by zephylac** [comment]
I'm not entirely satisfied, it respond well to MultiPolygon but it has a sequential processing. I'm not expert in PostgreSQL but I don't think we can achieve this via SQLAlchemy query.

**Comment by TimMcCauley** [comment]
@zephylac I agree. So let's move forward with this sequential implementation.

What do you think about create real plpgsql functions instead of using sqlalchemy + geoalchemy? As you already have pointed out, these methods in python become super explosive and very hard to read.. I think we should keep this logic entirely in the backend long term.

In regards to plpgsql: I don't have much experience with it but the syntax is pretty straight forward and fairly easy to understand with a little SQL knowledge.

https://www.postgresql.org/docs/9.2/plpgsql.html

Also sorry for this late response, I have been travelling quite a bit lately..

2 further questions: 
- would you be willing to join our rocket.chat to discuss these issues in more detail?
- did the collaborator invitation work?

**Comment by zephylac** [comment]
> would you be willing to join our rocket.chat to discuss these issues in more detail?
 * yes it would be easier to talk about it
> did the collaborator invitation work?
 * yes

**Pull request merged**
